INSERT INTO Cartas (nombre, valor_nutrimental, tipo) VALUES
('Bread', 4, 'Side'),
('Chicken', 2, 'Protein'),
('Tongs', 3, 'Utils'),
('Grill', 2, 'Utils'),
('Feta Cheese', 3, 'Vegetable'),
('Cherry Tomatoes', 2, 'Vegetable'),
('Egg', 8, 'Protein'),
('Ham', 7, 'Protein'),
('Onion', 6, 'Vegetable'),
('Bacon', 7, 'Vegetable'),
('Knife', 6, 'Utils'),
('Bowl', 8, 'Utils'),
('Olive Oil', 7, 'Side'),
('Salt', 5, 'Side'),
('Turkey', 3, 'Protein'),
('Potatoes', 4, 'Side'),
('Carrot', 4, 'Vegetable'),
('Brussels Sprouts', 3, 'Vegetable'),
('Oven', 3, 'Utils'),
('Pot', 4, 'Utils'),
('Wooden Spoon', 4, 'Utils'),
('Rice', 3, 'Side'),
('Cranberry Sauce', 5, 'Side'),
('Pork', 8, 'Protein'),
('Cutting Board', 6, 'Utils'),
('Thermometer', 8, 'Utils'),
('Mustard', 6, 'Side'),
('Apple Cider', 7, 'Side'),
('Salmon', 3, 'Protein'),
('Heavy Cream', 4, 'Side'),
('Pan', 2, 'Utils'),
('Mixer', 3, 'Utils'),
('Lemon', 2, 'Side'),
('Asparagus', 3, 'Vegetable'),
('Chocolate', 4, 'Protein'),
('Strawberry', 3, 'Vegetable'),
('Rosemary', 3, 'Vegetable'),
('Butter', 7, 'Side'),
('Sugar', 6, 'Side'),
('Flour', 8, 'Protein'),
('Rolling Pin', 6, 'Utils'),
('Molds', 7, 'Utils'),
('White Fondant', 9, 'Vegetable'),
('Jam', 7, 'Vegetable'),
('Olives', 4, 'Side'),
('Salad', 3, 'Vegetable'),
('more-time', 0, 'Special'),
('less-points', 0, 'Special');
